//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDemo.NGPDemo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eCertWebServiceProvider", ConfigurationName="NGPDemo.WebServiceProviderSoap")]
    public interface WebServiceProviderSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/IsAlive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IsAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/IsAlive", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsAliveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/Providername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Providername();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/Providername", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ProvidernameAsync();
        
        // CODEGEN: Generating message contract since message GetDataRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIDemo.NGPDemo.GetDataResponse GetData(APIDemo.NGPDemo.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<APIDemo.NGPDemo.GetDataResponse> GetDataAsync(APIDemo.NGPDemo.GetDataRequest request);
        
        // CODEGEN: Generating message contract since message GetDataSchemaRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/GetDataSchema", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIDemo.NGPDemo.GetDataSchemaResponse GetDataSchema(APIDemo.NGPDemo.GetDataSchemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/GetDataSchema", ReplyAction="*")]
        System.Threading.Tasks.Task<APIDemo.NGPDemo.GetDataSchemaResponse> GetDataSchemaAsync(APIDemo.NGPDemo.GetDataSchemaRequest request);
        
        // CODEGEN: Generating message contract since message GetDataParameterSchemaRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/GetDataParameterSchema", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIDemo.NGPDemo.GetDataParameterSchemaResponse GetDataParameterSchema(APIDemo.NGPDemo.GetDataParameterSchemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/GetDataParameterSchema", ReplyAction="*")]
        System.Threading.Tasks.Task<APIDemo.NGPDemo.GetDataParameterSchemaResponse> GetDataParameterSchemaAsync(APIDemo.NGPDemo.GetDataParameterSchemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Login(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LoginAsync(string Username, string Password);
        
        // CODEGEN: Generating message contract since message LogoutRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIDemo.NGPDemo.LogoutResponse Logout(APIDemo.NGPDemo.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<APIDemo.NGPDemo.LogoutResponse> LogoutAsync(APIDemo.NGPDemo.LogoutRequest request);
        
        // CODEGEN: Generating message contract since message SendDataRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/SendData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIDemo.NGPDemo.SendDataResponse SendData(APIDemo.NGPDemo.SendDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/SendData", ReplyAction="*")]
        System.Threading.Tasks.Task<APIDemo.NGPDemo.SendDataResponse> SendDataAsync(APIDemo.NGPDemo.SendDataRequest request);
        
        // CODEGEN: Generating message contract since message GetSendDataSchemaRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/GetSendDataSchema", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIDemo.NGPDemo.GetSendDataSchemaResponse GetSendDataSchema(APIDemo.NGPDemo.GetSendDataSchemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/GetSendDataSchema", ReplyAction="*")]
        System.Threading.Tasks.Task<APIDemo.NGPDemo.GetSendDataSchemaResponse> GetSendDataSchemaAsync(APIDemo.NGPDemo.GetSendDataSchemaRequest request);
        
        // CODEGEN: Generating message contract since message MethodListGetDataRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/MethodListGetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIDemo.NGPDemo.MethodListGetDataResponse MethodListGetData(APIDemo.NGPDemo.MethodListGetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/MethodListGetData", ReplyAction="*")]
        System.Threading.Tasks.Task<APIDemo.NGPDemo.MethodListGetDataResponse> MethodListGetDataAsync(APIDemo.NGPDemo.MethodListGetDataRequest request);
        
        // CODEGEN: Generating message contract since message MethodListSendDataRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/MethodListSendData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIDemo.NGPDemo.MethodListSendDataResponse MethodListSendData(APIDemo.NGPDemo.MethodListSendDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/MethodListSendData", ReplyAction="*")]
        System.Threading.Tasks.Task<APIDemo.NGPDemo.MethodListSendDataResponse> MethodListSendDataAsync(APIDemo.NGPDemo.MethodListSendDataRequest request);
        
        // CODEGEN: Generating message contract since message GetTokenInfoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/GetTokenInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIDemo.NGPDemo.GetTokenInfoResponse GetTokenInfo(APIDemo.NGPDemo.GetTokenInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eCertWebServiceProvider/GetTokenInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<APIDemo.NGPDemo.GetTokenInfoResponse> GetTokenInfoAsync(APIDemo.NGPDemo.GetTokenInfoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eCertWebServiceProvider")]
    public partial class WebServiceProviderSOAPHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        private string languageField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        public WebServiceProviderSOAPHeader() {
            this.usernameField = "";
            this.passwordField = "";
            this.tokenField = "00000000-0000-0000-0000-000000000000";
            this.languageField = "DE-DE";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute("00000000-0000-0000-0000-000000000000")]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute("DE-DE")]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://eCertWebServiceProvider", IsWrapped=true)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://eCertWebServiceProvider")]
        public APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eCertWebServiceProvider", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eCertWebServiceProvider", Order=1)]
        public System.Xml.XmlNode parameter;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader, string name, System.Xml.XmlNode parameter) {
            this.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            this.name = name;
            this.parameter = parameter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://eCertWebServiceProvider", IsWrapped=true)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eCertWebServiceProvider", Order=0)]
        public System.Xml.XmlNode GetDataResult;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(System.Xml.XmlNode GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataSchema", WrapperNamespace="http://eCertWebServiceProvider", IsWrapped=true)]
    public partial class GetDataSchemaRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://eCertWebServiceProvider")]
        public APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eCertWebServiceProvider", Order=0)]
        public string name;
        
        public GetDataSchemaRequest() {
        }
        
        public GetDataSchemaRequest(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader, string name) {
            this.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataSchemaResponse", WrapperNamespace="http://eCertWebServiceProvider", IsWrapped=true)]
    public partial class GetDataSchemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eCertWebServiceProvider", Order=0)]
        public System.Xml.XmlNode GetDataSchemaResult;
        
        public GetDataSchemaResponse() {
        }
        
        public GetDataSchemaResponse(System.Xml.XmlNode GetDataSchemaResult) {
            this.GetDataSchemaResult = GetDataSchemaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataParameterSchema", WrapperNamespace="http://eCertWebServiceProvider", IsWrapped=true)]
    public partial class GetDataParameterSchemaRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://eCertWebServiceProvider")]
        public APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eCertWebServiceProvider", Order=0)]
        public string name;
        
        public GetDataParameterSchemaRequest() {
        }
        
        public GetDataParameterSchemaRequest(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader, string name) {
            this.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataParameterSchemaResponse", WrapperNamespace="http://eCertWebServiceProvider", IsWrapped=true)]
    public partial class GetDataParameterSchemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eCertWebServiceProvider", Order=0)]
        public System.Xml.XmlNode GetDataParameterSchemaResult;
        
        public GetDataParameterSchemaResponse() {
        }
        
        public GetDataParameterSchemaResponse(System.Xml.XmlNode GetDataParameterSchemaResult) {
            this.GetDataParameterSchemaResult = GetDataParameterSchemaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Logout", WrapperNamespace="http://eCertWebServiceProvider", IsWrapped=true)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://eCertWebServiceProvider")]
        public APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader) {
            this.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogoutResponse", WrapperNamespace="http://eCertWebServiceProvider", IsWrapped=true)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eCertWebServiceProvider", Order=0)]
        public System.Xml.XmlNode LogoutResult;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(System.Xml.XmlNode LogoutResult) {
            this.LogoutResult = LogoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendData", WrapperNamespace="http://eCertWebServiceProvider", IsWrapped=true)]
    public partial class SendDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://eCertWebServiceProvider")]
        public APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eCertWebServiceProvider", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eCertWebServiceProvider", Order=1)]
        public System.Xml.XmlNode parameter;
        
        public SendDataRequest() {
        }
        
        public SendDataRequest(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader, string name, System.Xml.XmlNode parameter) {
            this.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            this.name = name;
            this.parameter = parameter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendDataResponse", WrapperNamespace="http://eCertWebServiceProvider", IsWrapped=true)]
    public partial class SendDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eCertWebServiceProvider", Order=0)]
        public System.Xml.XmlNode SendDataResult;
        
        public SendDataResponse() {
        }
        
        public SendDataResponse(System.Xml.XmlNode SendDataResult) {
            this.SendDataResult = SendDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSendDataSchema", WrapperNamespace="http://eCertWebServiceProvider", IsWrapped=true)]
    public partial class GetSendDataSchemaRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://eCertWebServiceProvider")]
        public APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eCertWebServiceProvider", Order=0)]
        public string name;
        
        public GetSendDataSchemaRequest() {
        }
        
        public GetSendDataSchemaRequest(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader, string name) {
            this.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSendDataSchemaResponse", WrapperNamespace="http://eCertWebServiceProvider", IsWrapped=true)]
    public partial class GetSendDataSchemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eCertWebServiceProvider", Order=0)]
        public System.Xml.XmlNode GetSendDataSchemaResult;
        
        public GetSendDataSchemaResponse() {
        }
        
        public GetSendDataSchemaResponse(System.Xml.XmlNode GetSendDataSchemaResult) {
            this.GetSendDataSchemaResult = GetSendDataSchemaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MethodListGetData", WrapperNamespace="http://eCertWebServiceProvider", IsWrapped=true)]
    public partial class MethodListGetDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://eCertWebServiceProvider")]
        public APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader;
        
        public MethodListGetDataRequest() {
        }
        
        public MethodListGetDataRequest(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader) {
            this.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MethodListGetDataResponse", WrapperNamespace="http://eCertWebServiceProvider", IsWrapped=true)]
    public partial class MethodListGetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eCertWebServiceProvider", Order=0)]
        public System.Xml.XmlNode MethodListGetDataResult;
        
        public MethodListGetDataResponse() {
        }
        
        public MethodListGetDataResponse(System.Xml.XmlNode MethodListGetDataResult) {
            this.MethodListGetDataResult = MethodListGetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MethodListSendData", WrapperNamespace="http://eCertWebServiceProvider", IsWrapped=true)]
    public partial class MethodListSendDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://eCertWebServiceProvider")]
        public APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader;
        
        public MethodListSendDataRequest() {
        }
        
        public MethodListSendDataRequest(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader) {
            this.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MethodListSendDataResponse", WrapperNamespace="http://eCertWebServiceProvider", IsWrapped=true)]
    public partial class MethodListSendDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eCertWebServiceProvider", Order=0)]
        public System.Xml.XmlNode MethodListSendDataResult;
        
        public MethodListSendDataResponse() {
        }
        
        public MethodListSendDataResponse(System.Xml.XmlNode MethodListSendDataResult) {
            this.MethodListSendDataResult = MethodListSendDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenInfo", WrapperNamespace="http://eCertWebServiceProvider", IsWrapped=true)]
    public partial class GetTokenInfoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://eCertWebServiceProvider")]
        public APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader;
        
        public GetTokenInfoRequest() {
        }
        
        public GetTokenInfoRequest(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader) {
            this.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenInfoResponse", WrapperNamespace="http://eCertWebServiceProvider", IsWrapped=true)]
    public partial class GetTokenInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eCertWebServiceProvider", Order=0)]
        public System.Xml.XmlNode GetTokenInfoResult;
        
        public GetTokenInfoResponse() {
        }
        
        public GetTokenInfoResponse(System.Xml.XmlNode GetTokenInfoResult) {
            this.GetTokenInfoResult = GetTokenInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceProviderSoapChannel : APIDemo.NGPDemo.WebServiceProviderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceProviderSoapClient : System.ServiceModel.ClientBase<APIDemo.NGPDemo.WebServiceProviderSoap>, APIDemo.NGPDemo.WebServiceProviderSoap {
        
        public WebServiceProviderSoapClient() {
        }
        
        public WebServiceProviderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceProviderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProviderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProviderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsAlive() {
            return base.Channel.IsAlive();
        }
        
        public System.Threading.Tasks.Task<bool> IsAliveAsync() {
            return base.Channel.IsAliveAsync();
        }
        
        public string Providername() {
            return base.Channel.Providername();
        }
        
        public System.Threading.Tasks.Task<string> ProvidernameAsync() {
            return base.Channel.ProvidernameAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIDemo.NGPDemo.GetDataResponse APIDemo.NGPDemo.WebServiceProviderSoap.GetData(APIDemo.NGPDemo.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public System.Xml.XmlNode GetData(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader, string name, System.Xml.XmlNode parameter) {
            APIDemo.NGPDemo.GetDataRequest inValue = new APIDemo.NGPDemo.GetDataRequest();
            inValue.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            inValue.name = name;
            inValue.parameter = parameter;
            APIDemo.NGPDemo.GetDataResponse retVal = ((APIDemo.NGPDemo.WebServiceProviderSoap)(this)).GetData(inValue);
            return retVal.GetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIDemo.NGPDemo.GetDataResponse> APIDemo.NGPDemo.WebServiceProviderSoap.GetDataAsync(APIDemo.NGPDemo.GetDataRequest request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIDemo.NGPDemo.GetDataResponse> GetDataAsync(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader, string name, System.Xml.XmlNode parameter) {
            APIDemo.NGPDemo.GetDataRequest inValue = new APIDemo.NGPDemo.GetDataRequest();
            inValue.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            inValue.name = name;
            inValue.parameter = parameter;
            return ((APIDemo.NGPDemo.WebServiceProviderSoap)(this)).GetDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIDemo.NGPDemo.GetDataSchemaResponse APIDemo.NGPDemo.WebServiceProviderSoap.GetDataSchema(APIDemo.NGPDemo.GetDataSchemaRequest request) {
            return base.Channel.GetDataSchema(request);
        }
        
        public System.Xml.XmlNode GetDataSchema(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader, string name) {
            APIDemo.NGPDemo.GetDataSchemaRequest inValue = new APIDemo.NGPDemo.GetDataSchemaRequest();
            inValue.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            inValue.name = name;
            APIDemo.NGPDemo.GetDataSchemaResponse retVal = ((APIDemo.NGPDemo.WebServiceProviderSoap)(this)).GetDataSchema(inValue);
            return retVal.GetDataSchemaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIDemo.NGPDemo.GetDataSchemaResponse> APIDemo.NGPDemo.WebServiceProviderSoap.GetDataSchemaAsync(APIDemo.NGPDemo.GetDataSchemaRequest request) {
            return base.Channel.GetDataSchemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIDemo.NGPDemo.GetDataSchemaResponse> GetDataSchemaAsync(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader, string name) {
            APIDemo.NGPDemo.GetDataSchemaRequest inValue = new APIDemo.NGPDemo.GetDataSchemaRequest();
            inValue.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            inValue.name = name;
            return ((APIDemo.NGPDemo.WebServiceProviderSoap)(this)).GetDataSchemaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIDemo.NGPDemo.GetDataParameterSchemaResponse APIDemo.NGPDemo.WebServiceProviderSoap.GetDataParameterSchema(APIDemo.NGPDemo.GetDataParameterSchemaRequest request) {
            return base.Channel.GetDataParameterSchema(request);
        }
        
        public System.Xml.XmlNode GetDataParameterSchema(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader, string name) {
            APIDemo.NGPDemo.GetDataParameterSchemaRequest inValue = new APIDemo.NGPDemo.GetDataParameterSchemaRequest();
            inValue.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            inValue.name = name;
            APIDemo.NGPDemo.GetDataParameterSchemaResponse retVal = ((APIDemo.NGPDemo.WebServiceProviderSoap)(this)).GetDataParameterSchema(inValue);
            return retVal.GetDataParameterSchemaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIDemo.NGPDemo.GetDataParameterSchemaResponse> APIDemo.NGPDemo.WebServiceProviderSoap.GetDataParameterSchemaAsync(APIDemo.NGPDemo.GetDataParameterSchemaRequest request) {
            return base.Channel.GetDataParameterSchemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIDemo.NGPDemo.GetDataParameterSchemaResponse> GetDataParameterSchemaAsync(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader, string name) {
            APIDemo.NGPDemo.GetDataParameterSchemaRequest inValue = new APIDemo.NGPDemo.GetDataParameterSchemaRequest();
            inValue.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            inValue.name = name;
            return ((APIDemo.NGPDemo.WebServiceProviderSoap)(this)).GetDataParameterSchemaAsync(inValue);
        }
        
        public string Login(string Username, string Password) {
            return base.Channel.Login(Username, Password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string Username, string Password) {
            return base.Channel.LoginAsync(Username, Password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIDemo.NGPDemo.LogoutResponse APIDemo.NGPDemo.WebServiceProviderSoap.Logout(APIDemo.NGPDemo.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public System.Xml.XmlNode Logout(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader) {
            APIDemo.NGPDemo.LogoutRequest inValue = new APIDemo.NGPDemo.LogoutRequest();
            inValue.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            APIDemo.NGPDemo.LogoutResponse retVal = ((APIDemo.NGPDemo.WebServiceProviderSoap)(this)).Logout(inValue);
            return retVal.LogoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIDemo.NGPDemo.LogoutResponse> APIDemo.NGPDemo.WebServiceProviderSoap.LogoutAsync(APIDemo.NGPDemo.LogoutRequest request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIDemo.NGPDemo.LogoutResponse> LogoutAsync(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader) {
            APIDemo.NGPDemo.LogoutRequest inValue = new APIDemo.NGPDemo.LogoutRequest();
            inValue.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            return ((APIDemo.NGPDemo.WebServiceProviderSoap)(this)).LogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIDemo.NGPDemo.SendDataResponse APIDemo.NGPDemo.WebServiceProviderSoap.SendData(APIDemo.NGPDemo.SendDataRequest request) {
            return base.Channel.SendData(request);
        }
        
        public System.Xml.XmlNode SendData(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader, string name, System.Xml.XmlNode parameter) {
            APIDemo.NGPDemo.SendDataRequest inValue = new APIDemo.NGPDemo.SendDataRequest();
            inValue.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            inValue.name = name;
            inValue.parameter = parameter;
            APIDemo.NGPDemo.SendDataResponse retVal = ((APIDemo.NGPDemo.WebServiceProviderSoap)(this)).SendData(inValue);
            return retVal.SendDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIDemo.NGPDemo.SendDataResponse> APIDemo.NGPDemo.WebServiceProviderSoap.SendDataAsync(APIDemo.NGPDemo.SendDataRequest request) {
            return base.Channel.SendDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIDemo.NGPDemo.SendDataResponse> SendDataAsync(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader, string name, System.Xml.XmlNode parameter) {
            APIDemo.NGPDemo.SendDataRequest inValue = new APIDemo.NGPDemo.SendDataRequest();
            inValue.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            inValue.name = name;
            inValue.parameter = parameter;
            return ((APIDemo.NGPDemo.WebServiceProviderSoap)(this)).SendDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIDemo.NGPDemo.GetSendDataSchemaResponse APIDemo.NGPDemo.WebServiceProviderSoap.GetSendDataSchema(APIDemo.NGPDemo.GetSendDataSchemaRequest request) {
            return base.Channel.GetSendDataSchema(request);
        }
        
        public System.Xml.XmlNode GetSendDataSchema(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader, string name) {
            APIDemo.NGPDemo.GetSendDataSchemaRequest inValue = new APIDemo.NGPDemo.GetSendDataSchemaRequest();
            inValue.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            inValue.name = name;
            APIDemo.NGPDemo.GetSendDataSchemaResponse retVal = ((APIDemo.NGPDemo.WebServiceProviderSoap)(this)).GetSendDataSchema(inValue);
            return retVal.GetSendDataSchemaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIDemo.NGPDemo.GetSendDataSchemaResponse> APIDemo.NGPDemo.WebServiceProviderSoap.GetSendDataSchemaAsync(APIDemo.NGPDemo.GetSendDataSchemaRequest request) {
            return base.Channel.GetSendDataSchemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIDemo.NGPDemo.GetSendDataSchemaResponse> GetSendDataSchemaAsync(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader, string name) {
            APIDemo.NGPDemo.GetSendDataSchemaRequest inValue = new APIDemo.NGPDemo.GetSendDataSchemaRequest();
            inValue.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            inValue.name = name;
            return ((APIDemo.NGPDemo.WebServiceProviderSoap)(this)).GetSendDataSchemaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIDemo.NGPDemo.MethodListGetDataResponse APIDemo.NGPDemo.WebServiceProviderSoap.MethodListGetData(APIDemo.NGPDemo.MethodListGetDataRequest request) {
            return base.Channel.MethodListGetData(request);
        }
        
        public System.Xml.XmlNode MethodListGetData(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader) {
            APIDemo.NGPDemo.MethodListGetDataRequest inValue = new APIDemo.NGPDemo.MethodListGetDataRequest();
            inValue.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            APIDemo.NGPDemo.MethodListGetDataResponse retVal = ((APIDemo.NGPDemo.WebServiceProviderSoap)(this)).MethodListGetData(inValue);
            return retVal.MethodListGetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIDemo.NGPDemo.MethodListGetDataResponse> APIDemo.NGPDemo.WebServiceProviderSoap.MethodListGetDataAsync(APIDemo.NGPDemo.MethodListGetDataRequest request) {
            return base.Channel.MethodListGetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIDemo.NGPDemo.MethodListGetDataResponse> MethodListGetDataAsync(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader) {
            APIDemo.NGPDemo.MethodListGetDataRequest inValue = new APIDemo.NGPDemo.MethodListGetDataRequest();
            inValue.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            return ((APIDemo.NGPDemo.WebServiceProviderSoap)(this)).MethodListGetDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIDemo.NGPDemo.MethodListSendDataResponse APIDemo.NGPDemo.WebServiceProviderSoap.MethodListSendData(APIDemo.NGPDemo.MethodListSendDataRequest request) {
            return base.Channel.MethodListSendData(request);
        }
        
        public System.Xml.XmlNode MethodListSendData(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader) {
            APIDemo.NGPDemo.MethodListSendDataRequest inValue = new APIDemo.NGPDemo.MethodListSendDataRequest();
            inValue.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            APIDemo.NGPDemo.MethodListSendDataResponse retVal = ((APIDemo.NGPDemo.WebServiceProviderSoap)(this)).MethodListSendData(inValue);
            return retVal.MethodListSendDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIDemo.NGPDemo.MethodListSendDataResponse> APIDemo.NGPDemo.WebServiceProviderSoap.MethodListSendDataAsync(APIDemo.NGPDemo.MethodListSendDataRequest request) {
            return base.Channel.MethodListSendDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIDemo.NGPDemo.MethodListSendDataResponse> MethodListSendDataAsync(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader) {
            APIDemo.NGPDemo.MethodListSendDataRequest inValue = new APIDemo.NGPDemo.MethodListSendDataRequest();
            inValue.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            return ((APIDemo.NGPDemo.WebServiceProviderSoap)(this)).MethodListSendDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIDemo.NGPDemo.GetTokenInfoResponse APIDemo.NGPDemo.WebServiceProviderSoap.GetTokenInfo(APIDemo.NGPDemo.GetTokenInfoRequest request) {
            return base.Channel.GetTokenInfo(request);
        }
        
        public System.Xml.XmlNode GetTokenInfo(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader) {
            APIDemo.NGPDemo.GetTokenInfoRequest inValue = new APIDemo.NGPDemo.GetTokenInfoRequest();
            inValue.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            APIDemo.NGPDemo.GetTokenInfoResponse retVal = ((APIDemo.NGPDemo.WebServiceProviderSoap)(this)).GetTokenInfo(inValue);
            return retVal.GetTokenInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIDemo.NGPDemo.GetTokenInfoResponse> APIDemo.NGPDemo.WebServiceProviderSoap.GetTokenInfoAsync(APIDemo.NGPDemo.GetTokenInfoRequest request) {
            return base.Channel.GetTokenInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIDemo.NGPDemo.GetTokenInfoResponse> GetTokenInfoAsync(APIDemo.NGPDemo.WebServiceProviderSOAPHeader WebServiceProviderSOAPHeader) {
            APIDemo.NGPDemo.GetTokenInfoRequest inValue = new APIDemo.NGPDemo.GetTokenInfoRequest();
            inValue.WebServiceProviderSOAPHeader = WebServiceProviderSOAPHeader;
            return ((APIDemo.NGPDemo.WebServiceProviderSoap)(this)).GetTokenInfoAsync(inValue);
        }
    }
}
